site_name: defectpl
site_url: https://github.com/Shibu778/defectpl
nav:
  - "Home": index.md
  - "Getting Started": getting_started.md
  - "Installation": installation.md
  - "Usage": usage.md
  - "Tutorials": tutorials.md
  - "API": api_reference.md

theme: readthedocs
